In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__ # pandas version check

'1.4.3'

In [3]:
np.__version__

'1.23.1'

In [4]:
array=np.arange(100,105)
array

array([100, 101, 102, 103, 104])

In [5]:
sr1=pd.Series(array)
sr1

0    100
1    101
2    102
3    103
4    104
dtype: int32

In [6]:
sr2=pd.Series(array, dtype="str")
sr2

0    100
1    101
2    102
3    103
4    104
dtype: object

In [7]:
sr3=pd.Series(["대리","차장","사원","팀장","사장"])
sr3

0    대리
1    차장
2    사원
3    팀장
4    사장
dtype: object

In [8]:
sr3.index

RangeIndex(start=0, stop=5, step=1)

In [9]:
sr3[3]

'팀장'

In [10]:
sr3[-1] # RangeIndex가 0부터 5까지라고 나와있기 때문에, 음수 인덱스는 불가능하다.

KeyError: -1

In [ ]:
sr3.index=["a","b","c","d","e"]
sr3

a    대리
b    차장
c    사원
d    팀장
e    사장
dtype: object

In [ ]:
sr3.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
sr3[3]

'팀장'

In [ ]:
sr3[-1]

'사장'

In [11]:
sr1.index=list("abcde")
sr1

a    100
b    101
c    102
d    103
e    104
dtype: int32

In [12]:
sr3.values

array(['대리', '차장', '사원', '팀장', '사장'], dtype=object)

In [13]:
sr1.values

array([100, 101, 102, 103, 104])

In [14]:
sr1.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [15]:
sr1[-2]

103

In [16]:
sr1.values[-2]

103

In [17]:
sr1.ndim

1

In [18]:
sr3.ndim

1

In [19]:
sr1.shape

(5,)

In [20]:
sr3.shape

(5,)

In [21]:
sr4=pd.Series(["영우","아린","나연",np.nan,"채영"])
sr4

0     영우
1     아린
2     나연
3    NaN
4     채영
dtype: object

# 연습문제 

In [22]:
arr=np.arange(50,55)
s1=pd.Series(arr, dtype="float32")
s1

0    50.0
1    51.0
2    52.0
3    53.0
4    54.0
dtype: float32

In [23]:
fruit_list=["apple",np.nan,"banana","kiwi","gubong"]
fruit_list

['apple', nan, 'banana', 'kiwi', 'gubong']

In [24]:
s2=pd.Series(fruit_list)
s2.index=["가","나","다","라","마"]
s2

가     apple
나       NaN
다    banana
라      kiwi
마    gubong
dtype: object

In [25]:
sr3

0    대리
1    차장
2    사원
3    팀장
4    사장
dtype: object

In [26]:
sr3["a"]

KeyError: 'a'

In [ ]:
sr3[0]

'대리'

In [ ]:
sr3[-5]

'대리'

In [ ]:
boolean_index=[True,True,False,False,True]
sr3[boolean_index]

a    대리
b    차장
e    사장
dtype: object

In [ ]:
sr1

a    100
b    101
c    102
d    103
e    104
dtype: int32

In [ ]:
sr1>102

a    False
b    False
c    False
d     True
e     True
dtype: bool

In [ ]:
sr1[sr1>101]

c    102
d    103
e    104
dtype: int32

In [ ]:
sr4

0     영우
1     아린
2     나연
3    NaN
4     채영
dtype: object

In [ ]:
sr4.isna()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [ ]:
sr4[sr4.isna()]

3    NaN
dtype: object

In [ ]:
sr4.notnull()

0     True
1     True
2     True
3    False
4     True
dtype: bool

In [ ]:
sr4[sr4.notnull()]

0    영우
1    아린
2    나연
4    채영
dtype: object

In [ ]:
sr4

0     영우
1     아린
2     나연
3    NaN
4     채영
dtype: object

In [ ]:
sr4[0:2]

0    영우
1    아린
dtype: object

In [ ]:
sr1

a    100
b    101
c    102
d    103
e    104
dtype: int32

In [ ]:
sr1[0:2]

a    100
b    101
dtype: int32

In [ ]:
sr1["a":"c"] # 끝까지 포함된다.

a    100
b    101
c    102
dtype: int32

In [ ]:
df1=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]], columns=["a","b","c"], index=["d","e","f"])
df1

a  b  c
d  1  2  3
e  4  5  6
f  7  8  9

In [31]:
df2=pd.DataFrame({"name":["Amy","Merry","June"], "age":[25,25,29], "nationality":["korea","korea","USA"]})
df2

name  age nationality
0    Amy   25       korea
1  Merry   25       korea
2   June   29         USA

In [ ]:
df1.index

Index(['d', 'e', 'f'], dtype='object')

In [ ]:
df1.columns

Index(['a', 'b', 'c'], dtype='object')

In [ ]:
df1.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

In [ ]:
df1.dtypes

a    int64
b    int64
c    int64
dtype: object

In [ ]:
df2.values

array([['Amy', 25, 'korea'],
       ['Merry', 25, 'korea'],
       ['June', 29, 'USA']], dtype=object)

In [32]:
df2.dtypes

name           object
age             int64
nationality    object
dtype: object

In [ ]:
df1.T

d  e  f
a  1  4  7
b  2  5  8
c  3  6  9

In [ ]:
df2.T

0      1     2
name           Amy  Merry  June
age             25     25    29
nationality  korea  korea   USA

In [ ]:
df2.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
df2.index=list("ABC")
df2

name  age nationality
A    Amy   25       korea
B  Merry   25       korea
C   June   29         USA

In [ ]:
df2["name"]

A      Amy
B    Merry
C     June
Name: name, dtype: object

In [ ]:
df2["nationality"]

A    korea
B    korea
C      USA
Name: nationality, dtype: object

In [ ]:
type(df2["name"]) # Series

pandas.core.series.Series

In [ ]:
df2[["name","age"]] # slicing

name  age
A    Amy   25
B  Merry   25
C   June   29

In [33]:
df2

name  age nationality
0    Amy   25       korea
1  Merry   25       korea
2   June   29         USA

In [ ]:
df2.rename({"name":"nickname"}, axis=1, inplace=True)

In [ ]:
df2

nickname  age nationality
A      Amy   25       korea
B    Merry   25       korea
C     June   29         USA

In [ ]:
df2.rename({"A":"a"}, axis=0)

nickname  age nationality
a      Amy   25       korea
B    Merry   25       korea
C     June   29         USA

In [ ]:
df2

nickname  age nationality
A      Amy   25       korea
B    Merry   25       korea
C     June   29         USA

# 연습문제

In [ ]:
df=pd.DataFrame({"food":["KFC", "McDonald", "SchoolFood"],"price":[1000, 2000, 2500],"rating":[4.5, 3.9, 4.2]})
df

food  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2

In [ ]:
df[["food","rating"]]

food  rating
0         KFC     4.5
1    McDonald     3.9
2  SchoolFood     4.2

In [ ]:
df=df.rename({"food":"place"}, axis=1)
df

place  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2

In [2]:
from IPython.display import Image # pip install Ipython 명령어 내린 이후에, 불러오기.

In [3]:
excel=pd.read_excel("data/seoul_transportation.xlsx", engine="openpyxl") # pip install openpyxl, 안되는 경우 engine="openpyxl"도 넣어주기. 
excel.head()

대중교통구분  노선명      년월   승차총승객수
0    지하철  1호선  201711  8633618
1    지하철  1호선  201712  8737235
2    지하철  1호선  201801  8145989
3    지하철  1호선  201802  7273309
4    지하철  1호선  201803  8692551

In [4]:
excel_rail=pd.read_excel("data/seoul_transportation.xlsx", sheet_name="철도")
excel_rail.head()
# excel 파일에는 시트가 2장이 있었다. 하나는 버스, 하나는 철도이다.

대중교통구분  노선명      년월   승차총승객수
0    지하철  1호선  201711  8633618
1    지하철  1호선  201712  8737235
2    지하철  1호선  201801  8145989
3    지하철  1호선  201802  7273309
4    지하철  1호선  201803  8692551

In [5]:
# 모든 시트를 가져오는 방법 : sheet_name=None
excel=pd.read_excel("data/seoul_transportation.xlsx", sheet_name=None)
excel

{'철도':     대중교통구분    노선명      년월   승차총승객수
 0      지하철    1호선  201711  8633618
 1      지하철    1호선  201712  8737235
 2      지하철    1호선  201801  8145989
 3      지하철    1호선  201802  7273309
 4      지하철    1호선  201803  8692551
 ..     ...    ...     ...      ...
 596    지하철  우이신설선  201901  1263643
 597    지하철  우이신설선  201902  1102109
 598    지하철  우이신설선  201903  1402393
 599    지하철  우이신설선  201904  1403115
 600    지하철  우이신설선  201905  1469681
 
 [601 rows x 4 columns],
 '버스':    대중교통구분      년월     승차총승객수
 0      버스  201711  163443126
 1      버스  201712  162521011
 2      버스  201801  153335185
 3      버스  201802  134768582
 4      버스  201803  166177855
 5      버스  201804  160452595
 6      버스  201805  164390595
 7      버스  201806  156999747
 8      버스  201807  163736112
 9      버스  201808  160240197
 10     버스  201809  151311657
 11     버스  201810  165820934
 12     버스  201811  163017758
 13     버스  201812  158049446
 14     버스  201901  153037549
 15     버스  201902  131621925
 16     버스  201903 

In [39]:
excel.keys()

dict_keys(['철도', '버스'])

In [40]:
excel["철도"].head()


대중교통구분  노선명      년월   승차총승객수
0    지하철  1호선  201711  8633618
1    지하철  1호선  201712  8737235
2    지하철  1호선  201801  8145989
3    지하철  1호선  201802  7273309
4    지하철  1호선  201803  8692551

In [41]:
excel["버스"].head()

대중교통구분      년월     승차총승객수
0     버스  201711  163443126
1     버스  201712  162521011
2     버스  201801  153335185
3     버스  201802  134768582
4     버스  201803  166177855

In [6]:
excel_rail=pd.read_excel("data/seoul_transportation.xlsx", sheet_name="철도")
excel_rail.to_excel("data/sample_rail.xlsx", index=False, sheet_name="철도")

In [7]:
excel_bus=pd.read_excel("data/seoul_transportation.xlsx", sheet_name="버스")
excel_bus.to_excel("data/sample_bus.xlsx", index=False, sheet_name="버스")

In [44]:
excel_rail.head()

대중교통구분  노선명      년월   승차총승객수
0    지하철  1호선  201711  8633618
1    지하철  1호선  201712  8737235
2    지하철  1호선  201801  8145989
3    지하철  1호선  201802  7273309
4    지하철  1호선  201803  8692551

In [45]:
excel_bus.head()

대중교통구분      년월     승차총승객수
0     버스  201711  163443126
1     버스  201712  162521011
2     버스  201801  153335185
3     버스  201802  134768582
4     버스  201803  166177855

In [51]:
# 구글링 예제 코드
df1 = pd.DataFrame([["AAA", "BBB"]], columns=["Spam", "Egg"])  
df2 = pd.DataFrame([["ABC", "XYZ"]], columns=["Foo", "Bar"])  
with pd.ExcelWriter("path_to_file.xlsx") as writer:
    df1.to_excel(writer, sheet_name="Sheet1")  
    df2.to_excel(writer, sheet_name="Sheet2") 

In [8]:
with pd.ExcelWriter("sample_data.xlsx") as writer:
    excel_bus.to_excel(writer, sheet_name="버스")
    excel_rail.to_excel(writer, sheet_name="철도")